# appspec.yml

version: 20.04
os: ubuntu
files:
  - source: /
    destination: /home/ubuntu/ec2-user/com-eungsoo-blog
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
