# logging-system.yml

name: logging-system

on:
#  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
env:
  S3_BUCKET_NAME: jsj-bucket
  PROJECT_NAME: blog

jobs:
  build:
    runs-on : ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up JDK 1.8 
        uses: actions/setup-java@v1 
        with: 
         java-version: 1.8 
        
      - name: Grant execute permission for gradlew 
        run: chmod +x gradlew 
        shell: bash 
       
      - name: Build with Gradle
        run: ./gradlew build 
        shell: bash
        
      - name: Make zip file 
        run: zip -r ./cicd.zip .
        shell: bash 
        
      - name: Configure AWS credentials 
        uses: aws-actions/configure-aws-credentials@v1 
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          aws-region: ${{ secrets.AWS_REGION }} 
          
      - name: Upload to S3 
        run: aws s3 cp --region ap-northeast-2 ./cicd.zip s3://$S3_BUCKET_NAME/$PROJECT_NAME/cicd.zip
        
      - name: Code Deploy
        run: aws deploy create-deployment --application-name cicd-test-deploy --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name develop --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME/cicd.zip






